# Generated by Django 3.0 on 2020-08-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('quest_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quest_statement', models.CharField(max_length=200)),
                ('quest_status', models.BooleanField(default=True)),
                ('quest_category', models.CharField(choices=[('COC', 'Clash of Codes'), ('WEBER', 'Weber'), ('HOTKEYS', 'Hotkeys')], default='COC', help_text='question to selected based on the quiz name', max_length=100)),
            ],
        ),
    ]
