# Generated by Django 3.0 on 2020-09-03 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(max_length=100)),
                ('quest_ans', models.CharField(max_length=100)),
                ('quest_marks', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('quest_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('quest_statement', models.CharField(max_length=200)),
                ('quest_status', models.BooleanField(default=True)),
                ('quest_category', models.CharField(choices=[('COC', 'Clash of Codes'), ('WEBER', 'Weber'), ('HOTKEYS', 'Hotkeys')], default='COC', help_text='question to selected based on the quiz name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ans', models.CharField(blank=True, max_length=100, null=True)),
                ('user_correct_ans', models.BooleanField(blank=True, default=False, null=True)),
                ('user_quest_attempted', models.BooleanField(blank=True, default=False, null=True)),
                ('quest_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.AnswerModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_quiz_name', models.CharField(choices=[('COC', 'Clash of Codes'), ('WEBER', 'Weber'), ('HOTKEYS', 'Hotkeys')], default='COC', max_length=100)),
                ('user_quiz_attempted', models.BooleanField(default=False)),
                ('user_quiz_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionModel'),
        ),
    ]
