# Generated by Django 3.0 on 2020-08-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionModel',
        ),
    ]
