# Generated by Django 3.0 on 2020-08-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_answermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ans', models.CharField(blank=True, max_length=100, null=True)),
                ('user_correct_ans', models.BooleanField(blank=True, null=True)),
                ('user_quest_attempted', models.BooleanField(blank=True, default=False, null=True)),
                ('quest_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.AnswerModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
