# Generated by Django 3.0 on 2020-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswermodel',
            name='user_correct_ans',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
