# Generated by Django 3.0 on 2020-08-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200828_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='quiz_no_questions',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='user_quiz_score',
            field=models.IntegerField(default=0),
        ),
    ]
