# Generated by Django 3.0 on 2020-08-19 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
 


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('quiz_name', models.CharField(choices=[('COC', 'Clash of Codes'), ('WEBER', 'Weber'), ('HOTKEYS', 'Hotkeys')], default=('COC', 'Clash of Codes'), max_length=40)),
                ('team_name', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
