# Generated by Django 3.0 on 2020-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200821_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
